data:extend(
{
  {
    type = "item",
    name = "advanced-machine-parts",
    icon = "__Henrikshell__/graphics/icons/parts/advanced-machine-parts.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "bearings",
    
    stack_size = 100
  },
{
    type = "recipe",
    name = "advanced-machine-parts|aluminium",
    order = "aluminium",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"aluminium-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}}
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|ceramics",
    order = "ceramics",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"silicon-nitride", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|cobalt",
    order = "cobalt",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"cobalt-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|copper",
    order = "copper",
    category = "crafting-with-fluid",
    enabled=true,
    ingredients = {{"copper-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|gold",
    order = "gold",
    category = "crafting-with-fluid",
    enabled=true,
    ingredients = {{"gold-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|iron",
    order = "iron",
    category = "crafting-with-fluid",
    enabled=true,
    ingredients = {{"iron-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|nickel",
    order = "nickel",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"nickel-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|silver",
    order = "silver",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"silver-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|steel",
    order = "steel",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"steel-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|tin",
    order = "tin",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"tin-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|titanium",
    order = "titanium",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"titanium-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|tungsten",
    order = "tungsten",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"tungsten-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|zinc",
    order = "zinc",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"zinc-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|lead",
    order = "lead",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"lead-plate", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  }
  )