data:extend(
{
  {
    type = "recipe",
    name = "advanced-machine-parts|brass",
    order = "brass",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"brass-alloy", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|bronze",
    order = "bronze",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"bronze-alloy", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|cobalt-steel",
    order = "cobalt-steel",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"cobalt-steel-alloy", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|electrum",
    order = "electrum",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"electrum-alloy", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|gunmetal",
    order = "gunmetal",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"gunmetal-alloy", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|invar",
    order = "invar",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"invar-alloy", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|nitinol",
    order = "nitinol",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"nitinol-alloy", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|copper-tungsten",
    order = "copper-tungsten",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"copper-tungsten-alloy", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  {
    type = "recipe",
    name = "advanced-machine-parts|tungsten-carbide",
    order = "tungsten-carbide",
    category = "crafting-with-fluid",
    enabled=false,
    ingredients = {{"tungsten-carbide", 2},{type="fluid", name="lubricant", amount=1}},
    results = {{"advanced-machine-parts",1}},
  },
  }
  )