data:extend(
{
  {
    type = "recipe",
    name = "iron-gear-wheel|brass",
    order = "brass",
    enabled=false,
    ingredients = {{"brass-alloy", 2}},
    results = {{"iron-gear-wheel",1}},
  },
  {
    type = "recipe",
    name = "iron-gear-wheel|bronze",
    order = "bronze",
    enabled=false,
    ingredients = {{"bronze-alloy", 2}},
    results = {{"iron-gear-wheel",1}},
  },
  {
    type = "recipe",
    name = "iron-gear-wheel|cobalt-steel",
    order = "cobalt-steel",
    enabled=false,
    ingredients = {{"cobalt-steel-alloy", 2}},
    results = {{"iron-gear-wheel",1}},
  },
  {
    type = "recipe",
    name = "iron-gear-wheel|electrum",
    order = "electrum",
    enabled=false,
    ingredients = {{"electrum-alloy", 2}},
    results = {{"iron-gear-wheel",1}},
  },
  {
    type = "recipe",
    name = "iron-gear-wheel|gunmetal",
    order = "gunmetal",
    enabled=false,
    ingredients = {{"gunmetal-alloy", 2}},
    results = {{"iron-gear-wheel",1}},
  },
  {
    type = "recipe",
    name = "iron-gear-wheel|invar",
    order = "invar",
    enabled=false,
    ingredients = {{"invar-alloy", 2}},
    results = {{"iron-gear-wheel",1}},
  },
  {
    type = "recipe",
    name = "iron-gear-wheel|nitinol",
    order = "nitinol",
    enabled=false,
    ingredients = {{"nitinol-alloy", 2}},
    results = {{"iron-gear-wheel",1}},
  },
  {
    type = "recipe",
    name = "iron-gear-wheel|copper-tungsten",
    order = "copper-tungsten",
    enabled=false,
    ingredients = {{"copper-tungsten-alloy", 2}},
    results = {{"iron-gear-wheel",1}},
  },
  {
    type = "recipe",
    name = "iron-gear-wheel|tungsten-carbide",
    order = "tungsten-carbide",
    enabled=false,
    ingredients = {{"tungsten-carbide", 2}},
    results = {{"iron-gear-wheel",1}},
  },
  }
  )