data:extend(
{
  {
    type = "item",
    name = "plumbing",
    icon = "__Henrikshell__/graphics/icons/parts/plumbing.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "plumbing",
    
    stack_size = 100000
  },
  {
    type = "recipe",
    name = "plumbing|aluminium",
    order = "aluminium",
    enabled=false,
    ingredients = {{"aluminium-plate", 1}},
    results = {{"plumbing",4}}
  },
  {
    type = "recipe",
    name = "plumbing|ceramics",
    order = "ceramics",
    enabled=false,
    ingredients = {{"silicon-nitride", 1}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|cobalt",
    order = "cobalt",
    enabled=false,
    ingredients = {{"cobalt-plate", 3}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|copper",
    order = "copper",
    enabled=true,
    ingredients = {{"copper-plate", 5}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|gold",
    order = "gold",
    enabled=true,
    ingredients = {{"gold-plate", 20}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|iron",
    enabled=true,
    order = "iron",
    ingredients = {{"iron-plate", 2}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|nickel",
    order = "nickel",
    enabled=false,
    ingredients = {{"nickel-plate", 10}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|silver",
    order = "silver",
    enabled=false,
    ingredients = {{"silver-plate", 20}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|steel",
    order = "steel",
    enabled=false,
    ingredients = {{"steel-plate", 1}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|tin",
    order = "tin",
    enabled=false,
    ingredients = {{"tin-plate", 20}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|titanium",
    order = "titanium",
    enabled=false,
    ingredients = {{"titanium-plate", 1}},
    results = {{"plumbing",4}},
  },
  {
    type = "recipe",
    name = "plumbing|tungsten",
    order = "tungsten",
    enabled=false,
    ingredients = {{"tungsten-plate", 1}},
    results = {{"plumbing",4}},
  },
  {
    type = "recipe",
    name = "plumbing|zinc",
    order = "zinc",
    enabled=false,
    ingredients = {{"zinc-plate", 10}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|brass",
    order = "brass",
    enabled=false,
    ingredients = {{"brass-alloy", 4}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|bronze",
    order = "bronze",
    enabled=false,
    ingredients = {{"bronze-alloy", 3}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|cobalt-steel",
    order = "cobalt-steel",
    enabled=false,
    ingredients = {
    {"cobalt-steel-alloy", 1}
    },
    results = {{"plumbing",4}},
  },
  {
    type = "recipe",
    name = "plumbing|invar",
    order = "invar",
    enabled=false,
    ingredients = {
    {"invar-alloy", 1}
    },
    results = {{"plumbing",4}},
  },
  {
    type = "recipe",
    name = "plumbing|nitinol",
    order = "nitinol",
    enabled=false,
    ingredients = {
    {"nitinol-alloy", 1}
    },
    results = {{"plumbing",20}},
  },
  {
    type = "recipe",
    name = "plumbing|copper-tungsten",
    order = "copper-tungsten",
    enabled=false,
    ingredients = {
    {"copper-tungsten-alloy", 1}
    },
    results = {{"plumbing",4}},
  },
  {
    type = "recipe",
    name = "plumbing|tungsten-carbide",
    order = "tungsten-carbide",
    enabled=false,
    ingredients = {{"tungsten-carbide", 1}},
    results = {{"plumbing",20}},
  },
  {
    type = "recipe",
    name = "plumbing|plastic",
    order = "plastic",
    enabled=false,
    ingredients = {{"plastic-bar", 1}},
    results = {{"plumbing",2}},
  },
  {
    type = "recipe",
    name = "plumbing|stone-brick",
    order = "stone-brick",
    enabled=true,
    ingredients = {{"stone-brick", 5}},
    results = {{"plumbing",2}},
  },
    {
    type = "recipe",
    name = "plumbing|lead",
    order = "lead",
    enabled=false,
    ingredients = {{"lead-plate", 20}},
    results = {{"plumbing",2}},
  },
  }
  )