require("functions")
require("prototypes.menu-categories")
require("prototypes.recipe-categories")

--Ores--
require("prototypes.ores.stone-ore")
require("prototypes.ores.coal-ore")
require("prototypes.ores.lignite-ore")
require("prototypes.ores.tin-ore")
require("prototypes.ores.lead-ore")
require("prototypes.ores.quartz")
require("prototypes.ores.silver-ore")
require("prototypes.ores.zinc-ore")
require("prototypes.ores.gold-ore")
require("prototypes.ores.bauxite")
require("prototypes.ores.rutile")
require("prototypes.ores.tungsten-ore")
require("prototypes.ores.nickel-ore")
require("prototypes.ores.cobalt-ore")
require("prototypes.ores.hematite")
require("prototypes.ores.chalcopyrite")
require("prototypes.ores.sulfur")
require("prototypes.ores.fluorite")
require("prototypes.ores.uraninite")
require("prototypes.ores.cryolite")
require("prototypes.ores.gem-ore")
require("prototypes.ores.gems")
require("prototypes.ores.copper-ore")
require("prototypes.ores.iron-ore")



--Materials--
require("prototypes.materials.ash")
require("prototypes.materials.asphalt")
require("prototypes.materials.carbon")
require("prototypes.materials.coal-powder")
require("prototypes.materials.concrete")
require("prototypes.materials.dirt")
require("prototypes.materials.explosives")
require("prototypes.materials.glass")
require("prototypes.materials.gravel")
require("prototypes.materials.lithium-cobalt-oxide")
require("prototypes.materials.plastic-bar")
require("prototypes.materials.raw-fish")
require("prototypes.materials.raw-wood")
require("prototypes.materials.resin")
require("prototypes.materials.rubber")
require("prototypes.materials.sand")
require("prototypes.materials.silver-oxide")
require("prototypes.materials.stone")
require("prototypes.materials.stone-brick")
require("prototypes.materials.sulfur")
require("prototypes.materials.synthetic-wood")
require("prototypes.materials.wood")
require("prototypes.materials.waste-rock")

--Chemicals--
require("prototypes.chemicals.calcium")
require("prototypes.chemicals.chlorine")
require("prototypes.chemicals.electrolysis")
require("prototypes.chemicals.ferric-chloride-solution")
require("prototypes.chemicals.hydrogen")
require("prototypes.chemicals.hydrogen-chloride")
require("prototypes.chemicals.fluorites")
require("prototypes.chemicals.liquid-air")
require("prototypes.chemicals.liquid-fuel")
require("prototypes.chemicals.lithium")
require("prototypes.chemicals.lubricants")
require("prototypes.chemicals.magnesium")
require("prototypes.chemicals.nitric-acid")
require("prototypes.chemicals.nitrogen")
require("prototypes.chemicals.nitrogen-oxide")
require("prototypes.chemicals.nitrogen-dioxide")
require("prototypes.chemicals.oil-processing")
require("prototypes.chemicals.oxygen")
require("prototypes.chemicals.rocket-fuel")
require("prototypes.chemicals.salt")
require("prototypes.chemicals.silicates")
require("prototypes.chemicals.sodium-hydroxide")
require("prototypes.chemicals.sodium-nitrate")
require("prototypes.chemicals.solid-fuel")
require("prototypes.chemicals.uranium-fuel")
require("prototypes.chemicals.sulfurates")
require("prototypes.chemicals.water")

--Metalworking--
require("prototypes.metalworking.metal-waste")
require("prototypes.metalworking.aluminium")
require("prototypes.metalworking.cobalt")
require("prototypes.metalworking.copper")
require("prototypes.metalworking.gold")
require("prototypes.metalworking.iron")
require("prototypes.metalworking.lead")
require("prototypes.metalworking.nickel")
require("prototypes.metalworking.silver")
require("prototypes.metalworking.steel")
require("prototypes.metalworking.tin")
require("prototypes.metalworking.titanium")
require("prototypes.metalworking.tungsten")
require("prototypes.metalworking.zinc")

--Alloys--
require("prototypes.metalworking.alloys.brass-alloy")
require("prototypes.metalworking.alloys.bronze-alloy")
require("prototypes.metalworking.alloys.cobalt-steel-alloy")
require("prototypes.metalworking.alloys.tungsten-alloy")
require("prototypes.metalworking.alloys.invar-alloy")
require("prototypes.metalworking.alloys.nitinol-alloy")
require("prototypes.metalworking.alloys.solder-alloy")

--Parts--
require("prototypes.parts.basic-machine-parts")
require("prototypes.parts.advanced-machine-parts")
require("prototypes.parts.plumbing")
require("prototypes.parts.batteries")
require("prototypes.parts.engines")
require("prototypes.parts.satellite-parts")
require("prototypes.parts.sticks")
require("prototypes.parts.grinding-polishing")
require("prototypes.parts.house-parts")
require("prototypes.parts.basic-electric-cable")
require("prototypes.parts.advanced-electric-cable")
require("prototypes.parts.circuit-electric-cable")

--Assembling Machines--
require("prototypes.assembling-machines.assembly")

--Processors--
require("prototypes.processors.chemical-furnaces")
require("prototypes.processors.chemical-mixing-furnace")
require("prototypes.processors.chemical-plants")
require("prototypes.processors.crusher")
require("prototypes.processors.electrolyser")
require("prototypes.processors.furnace-1")
require("prototypes.processors.furnace-2")
require("prototypes.processors.furnace-3")
require("prototypes.processors.furnace-4")
require("prototypes.processors.mixing-furnace")
require("prototypes.processors.oil-refinery")
require("prototypes.processors.pumps")
require("prototypes.processors.sifter")
require("prototypes.processors.void-recipes")

--Electronics--
require("prototypes.electronics.components")
require("prototypes.electronics.boards")
require("prototypes.electronics.circuits")

--Energy--
require("prototypes.energy.accumulators")
require("prototypes.energy.boilers")
require("prototypes.energy.poles")
require("prototypes.energy.solar-panels-small")
require("prototypes.energy.solar-panels")
require("prototypes.energy.solar-panels-large")
require("prototypes.energy.steam-engines")
require("prototypes.energy.lamps")

--Mining--
require("prototypes.mining-tools.drills")
require("prototypes.mining-tools.areadrills")
require("prototypes.mining-tools.pumpjacks")
require("prototypes.mining-tools.axes")

--Storage--
require("prototypes.storage.chests")
require("prototypes.storage.barrels")
require("prototypes.storage.storage-tanks")
require("prototypes.storage.warehouses")
require("prototypes.storage.gas-canister")
require("prototypes.storage.fluid-canister")

--Logistics--
require("prototypes.logistics.transport-belts.basic-transport-belt")
require("prototypes.logistics.transport-belts.fast-transport-belt")
require("prototypes.logistics.transport-belts.express-transport-belt")
require("prototypes.logistics.transport-belts.green-transport-belt")
require("prototypes.logistics.transport-belts.purple-transport-belt")

require("prototypes.logistics.inserters.burner-inserter")
require("prototypes.logistics.inserters.long-handed-burner-inserter")
require("prototypes.logistics.inserters.basic-inserter")
require("prototypes.logistics.inserters.long-handed-inserter")
require("prototypes.logistics.inserters.basic-smart-inserter")
require("prototypes.logistics.inserters.basic-smart-long-inserter")
require("prototypes.logistics.inserters.fast-inserter")
require("prototypes.logistics.inserters.fast-long-handed-inserter")
require("prototypes.logistics.inserters.smart-inserter")
require("prototypes.logistics.inserters.smart-long-inserter")
require("prototypes.logistics.inserters.express-inserter")
require("prototypes.logistics.inserters.express-long-inserter")

require("prototypes.logistics.pipes.iron-pipe")

require("prototypes.logistics.vehicles.rail")
require("prototypes.logistics.vehicles.trains")
require("prototypes.logistics.vehicles.train-signals")
require("prototypes.logistics.vehicles.robots")
require("prototypes.logistics.vehicles.vehicles")

require("prototypes.logistics.logics.blueprints")
require("prototypes.logistics.logics.combinators")
require("prototypes.logistics.logics.wires")

require("prototypes.logistics.fluid-logistics")

--Science--
require("prototypes.science.science-pots")
require("prototypes.science.beacons")
require("prototypes.science.speed-modules")
require("prototypes.science.effectivity-modules")
require("prototypes.science.productivity-modules")
require("prototypes.science.alien-artifacts")
require("prototypes.science.labs")
require("prototypes.science.science-pot-producer")

--WAR--
require("prototypes.war.ammo")

--Technology--
require("prototypes.technology.automation")
require("prototypes.technology.lithium-processing")
require("prototypes.technology.tin-processing")
require("prototypes.technology.lead-processing")
require("prototypes.technology.electronics")
require("prototypes.technology.steel-processing")
require("prototypes.technology.zinc-processing")
require("prototypes.technology.brass-processing")
require("prototypes.technology.bronze-processing")
require("prototypes.technology.cobalt-processing")
require("prototypes.technology.aluminium-processing")
require("prototypes.technology.nickel-processing")
require("prototypes.technology.silicon-processing")
require("prototypes.technology.tungsten-processing")
require("prototypes.technology.tungsten-alloy")
require("prototypes.technology.titanium-processing")
require("prototypes.technology.oil-processing")
require("prototypes.technology.plastics")
require("prototypes.technology.advanced-electronics")
require("prototypes.technology.gold-processing")
require("prototypes.technology.advanced-electronics-2")
require("prototypes.technology.silver-processing")
require("prototypes.technology.advanced-electronics-3")
require("prototypes.technology.optics")
require("prototypes.technology.sulfur-processing")
require("prototypes.technology.battery")
require("prototypes.technology.accumulators")
require("prototypes.technology.advanced-material-processing")
require("prototypes.technology.advanced-material-processing-2")
require("prototypes.technology.advanced-material-processing-3")
require("prototypes.technology.areadrills")
require("prototypes.technology.electrolysers")
require("prototypes.technology.chemical-plants")
require("prototypes.technology.mixing-furnaces")
require("prototypes.technology.chemical-mixing-furnaces")
require("prototypes.technology.chemical-furnaces")
require("prototypes.technology.inserters-1")
require("prototypes.technology.smart-inserters-1")
require("prototypes.technology.inserters-2")
require("prototypes.technology.smart-inserters-2")
require("prototypes.technology.inserters-3")
require("prototypes.technology.crusher")
require("prototypes.technology.sifter")
require("prototypes.technology.pumps")
require("prototypes.technology.logistics")
require("prototypes.technology.warehouses")
require("prototypes.technology.fluid-storage")
require("prototypes.technology.fluid-handling")
require("prototypes.technology.boilers")
require("prototypes.technology.poles")
require("prototypes.technology.solar-panels")
require("prototypes.technology.steam-engines")
require("prototypes.technology.drills")
require("prototypes.technology.pumpjacks")
require("prototypes.technology.robotics")
require("prototypes.technology.flight")
require("prototypes.technology.laser")
require("prototypes.technology.electric-energy-distribution")
require("prototypes.technology.turrets")
require("prototypes.technology.walls")
require("prototypes.technology.toolbelt")
require("prototypes.technology.ceramics")
require("prototypes.technology.nitinol-processing")
require("prototypes.technology.cobalt-steel-processing")
require("prototypes.technology.invar-processing")
require("prototypes.technology.gem-processing")
require("prototypes.technology.engines")
require("prototypes.technology.void")
require("prototypes.technology.railway")

for i, drill in pairs(data.raw["mining-drill"]) do
  if not drill.storage_slots then drill.storage_slots = 8 end
end
for i, drill in pairs(data.raw["furnace"]) do
  if not drill.result_inventory_size then drill.result_inventory_size = 3 end
end