data:extend(
{
  {
    type = "item",
    name = "tin-dust",
    icon = "__Henrikshell__/graphics/icons/ore/tin-ore.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "tin-processing",
    order = "c-a-a[tin-dust]",
    stack_size = 200
  },
    {
    type = "item",
    name = "tin-concentrate",
    icon = "__Henrikshell__/graphics/icons/ore/tin-ore.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "tin-processing",
    order = "c-a-a[tin-dust]",
    stack_size = 200
  },
   {
    type = "item",
    name = "tin-slag-1",
    icon = "__Henrikshell__/graphics/icons/ore/tin-ore.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "tin-processing",
    order = "c-a-a[tin-dust]",
    stack_size = 200
  },
  {
    type = "item",
    name = "tin-slag-2",
    icon = "__Henrikshell__/graphics/icons/ore/tin-ore.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "tin-processing",
    order = "c-a-a[tin-dust]",
    stack_size = 200
  },
   {
    type = "item",
    name = "tin-crude",
    icon = "__Henrikshell__/graphics/icons/ore/tin-ore.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "tin-processing",
    order = "c-a-a[tin-dust]",
    stack_size = 200
  },
{
    type = "item",
    name = "tin-plate",
    icon = "__Henrikshell__/graphics/icons/metalworking/tin-plate.png",
    flags = {"goes-to-main-inventory"},
    subgroup = "tin-processing",
    order = "c-a-a[tin-plate]",
    stack_size = 200
  },
--Recipes--
  {
    type = "recipe",
    name = "tin-crushing",
    icon = "__Henrikshell__/graphics/icons/ore/tin-ore.png",
    category = "crusher",
    subgroup = "tin-processing",
    order="a-1",
    energy_required = 1,
    enabled = false,
    ingredients = {{"tin-ore", 10}},
    results = {{"tin-dust", 10},{"gravel",1}},
  },
  {
    type = "recipe",
    name = "tin-sifting",
    icon = "__Henrikshell__/graphics/icons/ore/tin-ore.png",
    category = "sifter",
    subgroup = "tin-processing",
    order="a-2",
    energy_required = 10,
    enabled = false,
    ingredients = {{"tin-dust", 10},{type="fluid", name="water", amount=10}},
    results = {{"tin-concentrate", 10},{"gravel",1},{"iron-oxide-crushed",1}},
  },
  {
    type = "recipe",
    name = "tin-roasting",
    icon = "__Henrikshell__/graphics/icons/ore/tin-ore.png",
    category = "smelting",
    subgroup = "tin-processing",
    order="a-3",
    energy_required = 3.5,
    enabled = false,
    ingredients = {{"tin-concentrate", 10},{"carbon",1},{"sand",1},{"calcium-oxide",1}},
    results = {{"tin-crude", 5},{"tin-slag-1",5}},
  },
  {
    type = "recipe",
    name = "tin-roasting-1",
    icon = "__Henrikshell__/graphics/icons/ore/tin-ore.png",
    category = "smelting",
    subgroup = "tin-processing",
    order="a-4",
    energy_required = 3.5,
    enabled = false,
    ingredients = {{"tin-slag-1", 10},{"carbon",1},{"iron-plate",1},{"calcium-oxide",1}},
    results = {{"tin-crude", 5},{"tin-slag-2",5}},
  },
    {
    type = "recipe",
    name = "tin-roasting-2",
    icon = "__Henrikshell__/graphics/icons/ore/tin-ore.png",
    category = "smelting",
    subgroup = "tin-processing",
    order="a-5",
    energy_required = 3.5,
    enabled = false,
    ingredients = {{"tin-slag-2", 1}},
    results = {{"tin-crude", 1}},
    --{"waste-slag",5}},
  },
  {
    type = "recipe",
    name = "tin-refining",
    icon = "__Henrikshell__/graphics/icons/metalworking/tin-plate.png",
    category = "smelting",
    subgroup = "tin-processing",
    order="a-6",
    energy_required = 1,
    enabled = false,
    ingredients = {{"tin-crude", 4}},
    results = {{"tin-plate", 4},{"iron-oxide-crushed",1},{"copper-ore",1}},
  },
}
)